cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/


before_script:
  - npm install

#build:
#  stage: build
#  only:
#  - master
#  script:
#  - npm run build
#  artifacts:
#    untracked: true

staging_deploy:
  stage: deploy
  only:
  - TEST
  environment:
    name: staging
    url: https://glamos.meteotest.ch
  variables:
    TIER: "test"
    REMOTE_USER: "glamos"
    REMOTE_HOST: "glamos.meteotest.ch"
    CI_VAR_SUFFIX: "TEST"
  script: ./deploy/runner.sh

eth_dev_deploy:
  stage: deploy
  only:
  - ETH-DEV
  environment:
    name: eth-dev
    url: https://dev.glamos.ch
  variables:
    # strangely only ENVIRONMENT=production works on ETH server
    TIER: "live"
    REMOTE_USER: "glpo-dev"
    REMOTE_HOST: "dev.glamos.ch"
    REMOTE_IDENTITY: "server2servertransfer.rsa"
    CI_VAR_SUFFIX: "ETH"
  script: ./deploy/runner.sh

eth_test_deploy:
  stage: deploy
  only:
  - ETH-TEST
  environment:
    name: eth-test
    url: https://test.glamos.ch
  variables:
    TIER: "live"
    REMOTE_USER: "glpo-test"
    REMOTE_HOST: "test.glamos.ch"
    REMOTE_IDENTITY: "server2servertransfer.rsa"
    CI_VAR_SUFFIX: "ETH"
  script: ./deploy/runner.sh

# NOTE: for ETH, we use their term 'PROD' instead of 'LIVE'
eth_prod_deploy:
  stage: deploy
  only:
  - ETH-PROD
  environment:
    name: eth-prod
    url: https://www.glamos.ch
  variables:
    TIER: "live"
    REMOTE_USER: "glpo-prod"
    REMOTE_HOST: "www.glamos.ch"
    REMOTE_IDENTITY: "server2servertransfer.rsa"
    CI_VAR_SUFFIX: "ETH"
  script: ./deploy/runner.sh
